"""fix migration

Revision ID: 916db931e6e3
Revises: 1fd2ae68a08e
Create Date: 2024-09-25 23:34:33.498629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916db931e6e3'
down_revision: Union[str, None] = '1fd2ae68a08e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('brand_id', sa.Integer(), nullable=True), schema='shopee')
    op.create_foreign_key(op.f('photos_brand_id_fkey'), 'photos', 'brands', ['brand_id'], ['id'], source_schema='shopee', referent_schema='shopee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('photos_brand_id_fkey'), 'photos', schema='shopee', type_='foreignkey')
    op.drop_column('photos', 'brand_id', schema='shopee')
    # ### end Alembic commands ###
